### PR TITLE
add mefisto.patch

### PR DESCRIPTION
**Pull request by looooo**
diff from freecad. But with this the mefisto algorythm crashes.

### CODE REVIEW

**Comment by trelau** [comment]
failing on windows https://github.com/trelau/SMESH/pull/46/checks?check_run_id=2701243910#step:8:826

Are saying this is not working (i.e., crashing) in FreeCAD?

**Comment by trelau** [comment]
also, maybe related to #45 ?

**Comment by trelau** [comment]
Maybe needs this as well? https://github.com/FreeCAD/FreeCAD/commit/abe8457cb3ce9119d7ff9d1ddcc9d048f5c2624a#diff-bebe5e8ad4ec215905068b359849b9fc1d5a79235c37d8e1217c43cc1c04c2a7

**Comment by looooo** [comment]
thanks @trelau, I will try again if it fixes the mefisto issue.

**Comment by trelau** [comment]
@looooo cool. i am working on adding a simple unit test for MEFISTO (just a simple box to make sure it runs). if that gets going then i'll probably cut a 9.6.0.2 release. i noticed that the 9.6.0.1 release on conda uses OCCT 7.5.2 (whereas the 9.6.0.1 release in this project was set to OCCT 7.5.1 at that time). it might be nice to explicitly list the OCCT version in the conda-feedstock we one doesn't get ahead of the other by accident?

**Comment by looooo** [comment]
tested and it fixes meshing in freecad with mefisto.

occt is pinned to x.x (which means 7.5 at this time, so there should be no difference if the minor version of occt is updated.) If this is an issue for this repo we might have to pin occt more strictly.

**Comment by trelau** [comment]
ah, I see. i had some downstream tools (pyOCCT and pySMESH) where i was trying to use the SMESH from conda but it used 7.5.2 and those projects were still on 7.5.1. No worries, I'm updating them all to 7.5.2.

**Comment by trelau** [comment]
@looooo btw...is SMESH working in FreeCAD for OSX? i never did figure out why the unit tests for osx in this project keep failing...

**Comment by looooo** [comment]
@trelau no it still fails on osx. This is related to clearing the mesh. Maybe we can check if there is any diff to the smesh version in freecad.

**Pull request merged**
