### PR TITLE
[WIP] netgen 6.2.2004 support

### PR DESCRIPTION
**Pull request by looooo**

### CODE REVIEW

**Comment by looooo** [comment]
there are some errors:
1. somehow `NEW_NETGEN_INTERFACE` is not set
2. no known conversion for argument 1 from `'netgen::OCCGeometry' to 'std::shared_ptr<netgen::NetgenGeometry>'`

**Comment by looooo** [comment]
ok, this works now with netgen 6.2.1808. The netgen package will be updated in the next days to 6.2.2004 then we can try rerun this PR and see if things also work on windows.

**Comment by looooo** [comment]
netgen from conda-forge was updated to 6.2.2004. so now this package should be used.

@wwmayer this should include the occt7.3 fixes you mention, maybe you can give it a try if it works for you without modifications.
@ hobbes1069 maybe you can give it a try on fedora/centos with netgen 6.2. 2004

**Comment by looooo** [comment]
Still netgen6.2.1808 is used for the appveyor build.

**Comment by hobbes1069** [comment]
Still not quite there...

https://hobbes1069.fedorapeople.org/smesh-netgen-build.log

**Comment by looooo** [comment]
You also need to enable:
`-D NEW_NETGEN_INTERFACE:BOOL=ON` for netgen6.2.2004. But I am not sure this is the problem in your build.

**Comment by looooo** [comment]
@trelau I would like to remove the NEW_NETGEN_INTERFACE variable and replace the conditionals with the patch version of netgen. Is there a way to get the patch version of netgen?

**Comment by trelau** [comment]
@looooo are you referring to things like this https://github.com/LaughlinResearch/SMESH/blob/0d92fdc1eecc55a37081014851dd1eabd65b1c91/CMakeLists.txt#L143 so you can do this https://github.com/LaughlinResearch/SMESH/blob/0d92fdc1eecc55a37081014851dd1eabd65b1c91/src/NETGENPlugin/NETGENPlugin_NETGEN_3D.cxx#L79-L90

**Comment by trelau** [comment]
looks like they don't put the "2004" in the package version that the current CMake keys off of https://github.com/NGSolve/netgen/blob/9ffb22c37fbd13ec6bb499a09a35ff8aa8daa51b/libsrc/include/mydefs.hpp#L14

i suspect netgen is going to keep changing. maybe instead of defining "new netgen interface", we should just manually supply the "2004"? reading the "mydefs.h" to get the version doesn't seem very robust, maybe supply all of the MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION during CMake? i guess then more source code might have to chance where the current interface is used?

**Comment by looooo** [comment]
@trelau Let's try to convince netgen to put the patch version into the cmake-config. Until this happen use the NEW_NETGEN_INTERFACE variable. I guess a user defined netgen patch variable is also a little bit difficult to communicate.
Btw. thanks for adding the linux pipeline.

**Comment by trelau** [comment]
@looooo made this if that is what you were suggesting https://github.com/NGSolve/netgen/issues/60

**Comment by looooo** [comment]
I see one issue with osx, which I don't know how to resolve:
```
../inc/Utils_ExceptHandlers.hxx:44:22: error: no type named 'set_unexpected' in namespace 'std'
  ~Unexpect() { std::set_unexpected(old); }
```

**Comment by trelau** [comment]
@looooo overall i think it looks good. looks like this still is building with netgen 6.2.1808.

given the ongoing changes with netgen and unexpected api changes, i think it would be good to include a basic netgen unit tests with the CI builds. i have a simple test built in the test folder, and BUILD_TESTS turned on, just not sure how to run it in conda. if we can get that incorporated, i think it would be worthwhile and catch issues before it rolls up into a release or conda-forge build. what do you think?

**Comment by trelau** [comment]
> I see one issue with osx, which I don't know how to resolve:
> 
> ```
> ../inc/Utils_ExceptHandlers.hxx:44:22: error: no type named 'set_unexpected' in namespace 'std'
>   ~Unexpect() { std::set_unexpected(old); }
> ```

hmm....guess we should add osx support to the workflow CI. i tried to guess at osx support for recent pyocct updates, but couldn't get a compiler to work on conda build...maybe i should try again on this project since it's a bit smaller scope.

this commented part out of the workflow was an attempt, so could use it as a starting point? https://github.com/LaughlinResearch/pyOCCT/blob/4becc643c4ee0c3babbc01a9ffd1edafbe86b68d/.github/workflows/ci.yml#L236

**Comment by looooo** [comment]
yes a test would be nice to have, also to give netgen developers an opportunity to run some basic smesh tests and see if interface-changes have effect on on smesh... https://github.com/NGSolve/netgen/issues/56#issuecomment-620547773

I guess we can directly build the test in the test section of the recipe.

**Comment by looooo** [comment]
seems like netgen 6.2.2004 needs c++17 std. But smesh has some issues with c++17:

osx:
```
../inc/Utils_ExceptHandlers.hxx:44:22: error: no type named 'set_unexpected' in namespace 'std'
  ~Unexpect() { std::set_unexpected(old); }
```
linux:
```
..\inc\GEOMUtils.hxx(119): error C2039: 'binary_function': is not a member of 'std'
```

A little bit annoying : (

**Comment by trelau** [comment]
@looooo hmm, annoying indeed. are there any noticeable technical improvements with 6.2.2004? that is, is it worth upgrading? i cant find any release notes other than a list of commits which isn't telling me anything?

**Comment by hobbes1069** [comment]
Unfortunately 2004 is what is on Fedora so I'm stuck with it either way.

**Comment by looooo** [comment]
>@looooo hmm, annoying indeed. are there any noticeable technical improvements with 6.2.2004? that is, is it worth upgrading? i cant find any release notes other than a list of commits which isn't telling me anything?

No I don't think so. But if we are able to setup a testing environment which is easily reprodiceable for netgen developers, and in turn the interface gets a little bit more stable, this might be a big advantage for smesh/freecad. So I think we should go for it.

**Comment by looooo** [comment]
annoying linker errors for windows :(
```
NETGENPlugin_Mesher.cxx.obj : error LNK2019: unresolved external symbol "public: __cdecl TDF_Transaction::TDF_Transaction(class TCollection_AsciiString const &)" (??0TDF_Transaction@@QEAA@AEBVTCollection_AsciiString@@@Z) referenced in function "public: void __cdecl TDF_Transaction::`default constructor closure'(void)" (??_FTDF_Transaction@@QEAAXXZ)
```

**Comment by hobbes1069** [comment]
Getting close!
```
[100%] Linking CXX executable test_Netgen
/usr/bin/cmake -E cmake_link_script CMakeFiles/test_Netgen.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -O2 -g -DNDEBUG  -Wl,--as-needed -rdynamic CMakeFiles/test_Netgen.dir/test/Netgen.t.cpp.o  -o test_Netgen  -Wl,-rpath,/builddir/build/BUILD/SMESH-8.3.0.3/build libNETGENPlugin.so.8.3.0.3 -lTKPRim libStdMeshers.so.8.3.0.3 libMEFISTO2.so.8.3.0.3 libSMESH.so.8.3.0.3 libDriverDAT.so.8.3.0.3 libDriverGMF.so.8.3.0.3 libDriverSTL.so.8.3.0.3 /usr/lib64/libTKSTL.so.7.4.0 libDriverUNV.so.8.3.0.3 libDriver.so.8.3.0.3 libSMESHControls.so.8.3.0.3 libSMESHUtils.so.8.3.0.3 libSMESHDS.so.8.3.0.3 libSMDS.so.8.3.0.3 /usr/lib64/libdouble-conversion.so /usr/lib64/liblz4.so /usr/lib64/liblzma.so /usr/lib64/libexpat.so /usr/lib64/libxml2.so /usr/lib64/libvtkIOInfovis.so.1 /usr/lib64/libvtkRenderingContextOpenGL2.so.1 /usr/lib64/libjpeg.so /usr/lib64/libtiff.so /usr/lib64/libvtkTestingRendering.so.1 /usr/lib64/libvtkViewsContext2D.so.1 /usr/lib64/libvtkFiltersProgrammable.so.1 /usr/lib64/libvtkFiltersVerdict.so.1 /usr/lib64/libvtkverdict.so.1 /usr/lib64/libvtkFiltersGeneric.so.1 /usr/lib64/libvtkPythonInterpreter.so.1 /usr/lib64/libpython3.8.so /usr/lib64/libvtkWrappingTools.a /usr/lib64/libvtkFiltersPython.so.1 /usr/lib64/libvtkTestingGenericBridge.so.1 /usr/lib64/libvtkDomainsChemistryOpenGL2.so.1 /usr/lib64/libvtkDomainsChemistry.so.1 /usr/lib64/libhdf5.so /usr/lib64/libsz.so /usr/lib64/libdl.so -lm /usr/lib64/libhdf5_hl.so /usr/lib64/libvtkIOAMR.so.1 /usr/lib64/libvtkFiltersAMR.so.1 /usr/lib64/libvtkIOExodus.so.1 /usr/lib64/libvtkRenderingVolumeOpenGL2.so.1 /usr/lib64/libGLEW.so /usr/lib64/libvtkImagingMath.so.1 /usr/lib64/libvtkFiltersFlowPaths.so.1 /usr/lib64/libvtkFiltersHyperTree.so.1 /usr/lib64/libvtkImagingStencil.so.1 /usr/lib64/libvtkFiltersParallelImaging.so.1 /usr/lib64/libvtkFiltersPoints.so.1 /usr/lib64/libvtkFiltersSMP.so.1 /usr/lib64/libvtkFiltersSelection.so.1 /usr/lib64/libjsoncpp.so /usr/lib64/libvtkIOParallel.so.1 /usr/lib64/libvtkIOGeometry.so.1 /usr/lib64/libvtkexodusII.so.1 /usr/lib64/libnetcdf.so /usr/lib64/libvtkIONetCDF.so.1 /usr/lib64/libvtkFiltersTopology.so.1 /usr/lib64/libsqlite3.so /usr/lib64/libvtkGUISupportQtSQL.so.1 /usr/lib64/libQt5Sql.so.5.14.2 /usr/lib64/libvtkViewsGeovis.so.1 /usr/lib64/libvtkGeovisCore.so.1 /usr/lib64/libproj.so /usr/lib64/libvtkIOAsynchronous.so.1 /usr/lib64/libvtkIOCityGML.so.1 /usr/lib64/libvtkIOEnSight.so.1 /usr/lib64/libvtkIOExportOpenGL2.so.1 /usr/lib64/libvtkInteractionImage.so.1 /usr/lib64/libvtkIOExportPDF.so.1 /usr/lib64/libvtkIOExport.so.1 /usr/lib64/libvtkRenderingGL2PSOpenGL2.so.1 /usr/lib64/libvtkgl2ps.so.1 /usr/lib64/libpng.so /usr/lib64/libvtklibharu.so.1 /usr/lib64/libvtkIOImport.so.1 /usr/lib64/libvtkIOLSDyna.so.1 /usr/lib64/libvtkIOMINC.so.1 /usr/lib64/libogg.so /usr/lib64/libvtkIOMovie.so.1 /usr/lib64/libtheoraenc.so /usr/lib64/libtheoradec.so /usr/lib64/libvtkIOMySQL.so.1 /usr/lib64/libvtkTestingIOSQL.so.1 /usr/lib64/libvtkIOPLY.so.1 /usr/lib64/libvtkIOParallelXML.so.1 /usr/lib64/libvtkIOPostgreSQL.so.1 /usr/lib64/libvtkIOSQL.so.1 /usr/lib64/libvtkIOSegY.so.1 /usr/lib64/libvtkIOTecplotTable.so.1 /usr/lib64/libvtkIOVeraOut.so.1 /usr/lib64/libvtkIOVideo.so.1 /usr/lib64/libvtkImagingStatistics.so.1 /usr/lib64/libvtkRenderingImage.so.1 /usr/lib64/libvtkImagingMorphological.so.1 /usr/lib64/libvtkRenderingLOD.so.1 /usr/lib64/libvtkPythonContext2D.so.1 /usr/lib64/libvtkWrappingPython38Core.so.1 /usr/lib64/libvtkRenderingParallel.so.1 /usr/lib64/libvtkFiltersParallel.so.1 /usr/lib64/libvtkParallelCore.so.1 /usr/lib64/libvtkIOLegacy.so.1 /usr/lib64/libvtkRenderingQt.so.1 /usr/lib64/libvtkFiltersTexture.so.1 /usr/lib64/libvtkViewsQt.so.1 /usr/lib64/libvtkGUISupportQt.so.1 /usr/lib64/libvtkRenderingOpenGL2.so.1 /usr/lib64/libSM.so /usr/lib64/libICE.so /usr/lib64/libX11.so /usr/lib64/libXext.so /usr/lib64/libXt.so /usr/lib64/libvtkViewsInfovis.so.1 /usr/lib64/libvtkChartsCore.so.1 /usr/lib64/libvtkRenderingContext2D.so.1 /usr/lib64/libvtkViewsCore.so.1 /usr/lib64/libvtkInteractionWidgets.so.1 /usr/lib64/libvtkFiltersHybrid.so.1 /usr/lib64/libvtkInteractionStyle.so.1 /usr/lib64/libvtkRenderingAnnotation.so.1 /usr/lib64/libvtkImagingColor.so.1 /usr/lib64/libvtkRenderingVolume.so.1 /usr/lib64/libvtkIOXML.so.1 /usr/lib64/libvtkIOXMLParser.so.1 /usr/lib64/libvtkIOCore.so.1 /usr/lib64/libvtkFiltersImaging.so.1 /usr/lib64/libvtkImagingGeneral.so.1 /usr/lib64/libvtkImagingSources.so.1 /usr/lib64/libvtkRenderingLabel.so.1 /usr/lib64/libvtkRenderingFreeType.so.1 /usr/lib64/libvtkRenderingCore.so.1 /usr/lib64/libvtkCommonColor.so.1 /usr/lib64/libvtkFiltersGeometry.so.1 /usr/lib64/libvtkInfovisLayout.so.1 /usr/lib64/libvtkInfovisCore.so.1 /usr/lib64/libvtkFiltersExtraction.so.1 /usr/lib64/libvtkFiltersStatistics.so.1 /usr/lib64/libvtkImagingFourier.so.1 /usr/lib64/libvtkFiltersModeling.so.1 /usr/lib64/libvtkFiltersSources.so.1 /usr/lib64/libvtkFiltersGeneral.so.1 /usr/lib64/libvtkCommonComputationalGeometry.so.1 /usr/lib64/libvtkFiltersCore.so.1 /usr/lib64/libvtkImagingHybrid.so.1 /usr/lib64/libvtkImagingCore.so.1 /usr/lib64/libvtkIOImage.so.1 /usr/lib64/libvtkCommonExecutionModel.so.1 /usr/lib64/libvtkCommonDataModel.so.1 /usr/lib64/libvtkCommonMisc.so.1 /usr/lib64/libvtkCommonSystem.so.1 /usr/lib64/libvtksys.so.1 /usr/lib64/libvtkCommonTransforms.so.1 /usr/lib64/libvtkCommonMath.so.1 /usr/lib64/libvtkDICOMParser.so.1 /usr/lib64/libvtkmetaio.so.1 /usr/lib64/libz.so /usr/lib64/libQt5Widgets.so.5.14.2 /usr/lib64/libQt5Gui.so.5.14.2 /usr/lib64/libQt5Core.so.5.14.2 /usr/lib64/libvtkWrappingJava.so.1 /usr/lib64/libvtkCommonCore.so.1 libSMESHMisc.so.8.3.0.3 libSMESHTrace.so.8.3.0.3 libSMESHBasics.so.8.3.0.3 /usr/lib64/libTKCDF.so.7.4.0 /usr/lib64/libTKMeshVS.so.7.4.0 /usr/lib64/libTKV3d.so.7.4.0 /usr/lib64/libTKMesh.so.7.4.0 /usr/lib64/libTKHLR.so.7.4.0 /usr/lib64/libTKService.so.7.4.0 -lGL -lX11 -lXext -lXmu -lXi -lfontconfig /usr/lib64/libfreetype.so /usr/lib64/libboost_filesystem.so -lboost_thread -lpthread /usr/lib64/libboost_chrono.so /usr/lib64/libboost_date_time.so /usr/lib64/libboost_atomic.so /usr/lib64/libTKOffset.so.7.4.0 /usr/lib64/libTKFillet.so.7.4.0 /usr/lib64/libTKBool.so.7.4.0 /usr/lib64/libTKBO.so.7.4.0 /usr/lib64/libTKShHealing.so.7.4.0 /usr/lib64/libTKPrim.so.7.4.0 /usr/lib64/libTKTopAlgo.so.7.4.0 /usr/lib64/libTKGeomAlgo.so.7.4.0 /usr/lib64/libTKBRep.so.7.4.0 /usr/lib64/libTKGeomBase.so.7.4.0 /usr/lib64/libTKG3d.so.7.4.0 /usr/lib64/libTKG2d.so.7.4.0 /usr/lib64/libTKMath.so.7.4.0 /usr/lib64/libTKernel.so.7.4.0 -lpthread -lrt -lstdc++ -ldl /usr/lib64/libtbb.so /usr/lib64/libtbbmalloc.so /usr/lib64/libnglib.so.6.2 /usr/lib64/libnginterface.so.6.2 /usr/lib64/libngstlvis.so.6.2 /usr/lib64/libngstl.so.6.2 /usr/lib64/libnggeom2dvis.so.6.2 /usr/lib64/libnggeom2d.so.6.2 /usr/lib64/libngcsgvis.so.6.2 /usr/lib64/libngcsg.so.6.2 /usr/lib64/libngmesh.so.6.2 /usr/lib64/libngvisual.so.6.2 /usr/lib64/libngocc.so.6.2 /usr/lib64/libngcore.so 
/usr/bin/ld: cannot find -lTKPRim
```

**Comment by looooo** [comment]
@hobbes1069 do you find this line in the cmake output:
"OpenCASCADE library directory: ${OpenCASCADE_LIBRARY_DIR}"

**Comment by hobbes1069** [comment]
```
-- OpenCASCADE include directory: /usr/include/opencascade
-- OpenCASCADE library directory: /usr/lib64
```

**Comment by hobbes1069** [comment]
Looks like the library is "TKPrim" not "TKPRim"

**Comment by hobbes1069** [comment]
Fixing the typo in CmakeLists.txt gets me a successful build but testing fails:
```
1: Test command: /builddir/build/BUILD/SMESH-8.3.0.3/build/test_Netgen "Mesh a box with tetrahedral elements."
1: Test timeout computed to be: 1500
1: sh: SMDS_MemoryLimit: command not found
1: Filters: Mesh a box with tetrahedral elements.
1: 
1: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1: test_Netgen is a Catch v2.11.0 host application.
1: Run with -? for options
1: 
1: -------------------------------------------------------------------------------
1: Mesh a box with tetrahedral elements.
1: -------------------------------------------------------------------------------
1: /builddir/build/BUILD/SMESH-8.3.0.3/test/Netgen.t.cpp:14
1: ...............................................................................
1: 
1: /builddir/build/BUILD/SMESH-8.3.0.3/test/Netgen.t.cpp:14: FAILED:
1: due to a fatal error condition:
1:   SIGSEGV - Segmentation violation signal
```

**Comment by trelau** [comment]
weird link error on windows https://github.com/LaughlinResearch/SMESH/pull/21/checks?check_run_id=664314250#step:6:819

but looks like that TDF_Transaction class is part of TKLCAF, so maybe link NETGENPlugin to that??? https://www.opencascade.com/doc/occt-7.4.0/refman/html/class_t_d_f___transaction.html

**Comment by looooo** [comment]
I will try, but there are more unresolved external symbols like:
```
NETGENPlugin_NETGEN_3D.cxx.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl netgen::OCCGeometry::FindEdges(class netgen::Mesh &,class netgen::MeshingParameters const &)const " (?FindEdges@OCCGeometry@netgen@@UEBAXAEAVMesh@2@AEBVMeshingParameters@2@@Z)
```

**Comment by hobbes1069** [comment]
Assuming it passes testing, should I rebuild the Fedora version for this change? Currently nothing it using it because I had to move FreeCAD to the bundled version.

**Comment by looooo** [comment]
> Currently nothing it using it because I had to move FreeCAD to the bundled version.

What does "bundled version" means for fedora packages?

> Assuming it passes testing, should I rebuild the Fedora version for this change?

For freecad it makes definetly sense to have it available. Not sure if the internal smesh in freecad ever will be updated to netgen 6.2.2004. I guess the more maintainable way is to use this smesh library. But make sure you pin the netgen version tightly to smesh and smesh tightly to freecad. So only allow using the same version of netgen and smesh at runtime as was used for the build.

**Comment by hobbes1069** [comment]
Well what I mean is I used to use system smesh for FreeCAD before it became impossible which is why I packaged smesh for Fedora. Since I changed to the version bundled in FreeCAD there are no consumers of the smesh package in Fedora.

I would like to move back to system smesh eventually :)

**Comment by looooo** [comment]
Does the internal smesh works for you?

**Comment by hobbes1069** [comment]
For now (I think). I'm still in dependency hell. With Fedora 32 I finally got on the Coin4 stack (YAY!) but immediately got bit by the fact the Fedora 32 has Qt 5.13.x which means PySide2 5.13.x which is not compatible with Python 3.8, guess what version of Python is in Fedora 32?

**Comment by hobbes1069** [comment]
Any thoughts on the failing test?

**Comment by looooo** [comment]
> For now (I think). I'm still in dependency hell. With Fedora 32 I finally got on the Coin4 stack (YAY!) but immediately got bit by the fact the Fedora 32 has Qt 5.13.x which means PySide2 5.13.x which is not compatible with Python 3.8, guess what version of Python is in Fedora 32?

For conda we are using qt5.12.5 + a patched pyside 5.13.x which does a quite good job:
https://github.com/conda-forge/pyside2-feedstock/pull/62

> Any thoughts on the failing test?
Sorry, I need to figure out the windows problem first. Don't ignore windows. It's a difficult child but we have to care about them all.

**Comment by looooo** [comment]
I added a patch to make the missing netgen functions available:
https://github.com/conda-forge/netgen-feedstock/blob/master/recipe/dll_header.patch

Locally this worked for me. Maybe there is still missing the TKLCAF library, but let's see if it works without first.

@trelau Can you give some instructions how to run the test? @hobbes1069 already reported about a failing test on fedora. I guess it's best to setup the test for conda and see if it is also failing for these environments.
Is setting BUILD_TEST all we need to do?

**Comment by looooo** [comment]
@trelau The test is linked against ${SMESH_LIBRARIES}. It would be nice if we can remove some of these libraries. Somehow there is a linking error (python) for linux. Maybe you can give a suggestion which libraries are really necessary.

**Comment by hobbes1069** [comment]
Thanks for all your hard work on this! I went ahead and applied the PR to Fedora smesh again and it builds fine, but of course the test still fails.

**Comment by trelau** [comment]
@looooo turning on `BUILD_TESTS` will build an exe for a simple netgen test, but i only have used it locally and not in CI, so i doubt the workflow is configured yet.

not sure why anything has to be linked to python now? is it netgen? does that now mean we'd have to build SMESH for each python version? either way, for pyOCCT, we found that you had to explicitly link to python libraries on linux, but not windows. seems strange. and still not sure why anything smesh needs linked to python 🤔

**Comment by looooo** [comment]
> not sure why anything has to be linked to python now? is it netgen? does that now mean we'd have to build SMESH for each python version? either way, for pyOCCT, we found that you had to explicitly link to python libraries on linux, but not windows. seems strange. and still not sure why anything smesh needs linked to python thinking

I never found a workaround for this. So we build smesh for different python since we build netgen with python bindings. I agree that this is not necessary. The question is if creating netgen without python dependency makes sense. I guess it should be possible to create a netgen-dev (headers), netgen-lib (nglib, ngcore) and a netgen-python package. Conda-forge allows to do this, but this also means more maintenance work. So in my eyes keeping smesh python dependent is the easier way to proceed.
But still, the necessary libraries should not depend on python. As far as I can tell, smesh only depends on nglib. So there shouldn't be python involved. I guess the python dependency of the linker is coming via vtk-libraries which are part of ${SMESH_LIBRARIES}.

So my idea was to add only really necessary libraries and not all libs listed in ${SMESH_LIBRARIES}.

@hobbes1069 do you have a log of the crash

**Comment by trelau** [comment]
what would you leave out of `${SMESH_LIBRARIES}?`

`set(SMESH_LIBRARIES Driver DriverDAT DriverGMF DriverSTL DriverUNV MEFISTO2 SMDS SMESH SMESHBasics SMESHControls SMESHDS SMESHMisc SMESHTrace SMESHUtils StdMeshers)`

looks like VTK is linked to SMESHControls and SMDS

**Comment by trelau** [comment]
@looooo i was testing out some new pyocct packages and noticed that now netgen 6.2.2004 is showing up...i didn't expect that. did you?
image

**Comment by looooo** [comment]
@trelau yes it shouldn't show up, but due to lazy pinning of netgen for previous smesh-packages there are a combination of smesh and latest netgen which the solver thinks to be compatible. For the future I guess we need to pin a minimum version of smesh in smesh-dependent packages. This should solve the issue for future packages. For now we need to get smesh updated. We still see a crash on the freecad side somewhere in netgen. Once that is solved I will try to clean this PR and we can update smesh. Best if this update also includes a version update (minor version if possible).

Sorry for this inconveniences, but knowing about these issues before the problems arise is pretty hard. I tried my best to do so (pinning netgen closely to smesh) but actually it didn't help a lot. At least we know what the issue is and how to avoid it for the future.

**Comment by looooo** [comment]
I am moving netgen6.2.2004 to broken for now:
https://github.com/conda-forge/cf-mark-broken/compare/master...looooo:patch-4

**Comment by trelau** [comment]
Superseded by https://github.com/trelau/SMESH/pull/31

**Pull request closed without merging**
