### PR TITLE
Update to SMESH 9.7.0

### PR DESCRIPTION
**Pull request by trelau**

### CODE REVIEW

**Comment by trelau** [comment]
@looooo working on updating to SMESH 9.7.0 if you're interested. things seem ok except for linux if anything jumps out at you https://github.com/trelau/SMESH/runs/3709059046?check_suite_focus=true#step:8:425

**Comment by looooo** [comment]
@trelau great news. is this ready for testing?

**Comment by trelau** [comment]
@looooo i think so. i merged this and cut a 9.7.0.0 release. those osx tests are still failing though...

**Comment by looooo** [comment]
https://github.com/conda-forge/smesh-feedstock/pull/50

I enabled the tests for osx and set  the optimization level to O1 for osx.

**Pull request merged**
