### PR TITLE
Int 32 test

### PR DESCRIPTION
**Pull request by looooo**
for the compatibility with freecad SALOME_USE_64BIT_IDS shouldn't be defined. What do you think @trelau?

### CODE REVIEW

**Comment by looooo** [comment]
https://github.com/conda-forge/smesh-feedstock/pull/60#issuecomment-1179732900

**Comment by trelau** [comment]
Not sure why tests are failing with that could not find catch2 error...

at a glance this output and what's just below it seems strange...

https://github.com/trelau/SMESH/runs/7283531656?check_suite_focus=true#step:8:518

**Comment by trelau** [comment]
Also it looks like there is a commit to use SMESH 9.9.0. I think that should be in a separate PR. That is, get this working for the "Int 32 test" and then update to 9.9 separately. Hard to know what impact that could have.

**Comment by looooo** [comment]
@trelau, there is a newer catch2 version which might be pulled. This new catch2 version has a new interface:
`catch_all.hpp`. So one way is to pin the old version. The other way is to update smesh to use the new interface.

Not sure why I updated to smesh v9.9.0. I guess this should be reverted.

In addition we see some linking issues with windows. Our guess is that windows still uses int64 although -DSALOME_USE_64BIT_IDS is not declared.

**Comment by trelau** [comment]
@looooo still relevant after #73 ?

**Comment by looooo** [comment]
No.

**Pull request closed without merging**
